### ISSUE TITLE
Abstract

### ISSUE THREAD

**Issue by oej** [rtcweb-wg/rtcweb-overview#1]
"This document gives an overview and context of a protocol suite
   intended for use with real-time applications that can be deployed in
   browsers - "real time communication on the Web"."

Later in the document you mention non-browsers such as gateways. Do you want to include them in the abstract?
..."to make sure  all the parts"...

I feel that "that" is missing between "sure" and "all"

**Comment by alvestrand** [comment]
1. Not really - the focus here is that it has to be usable on the Web. There's time enough to mention non-browsers later in the document.
2. My English sense says that the sentence works both with and without "that" - I'll defer to native speakers of US-English for this one.

**Comment by alvestrand** [comment]
Closing as "no change needed" (editor's judgment).
